version: "3.5"

services:
    web:
      image: web
      build:
        context: web
      ports:
      - 80:80
    api:
      image: api
      build:
        context: api
      ports:
      - 8080:8080