name: build-frontend

on:
  push:
    branches:
    - "master"
    paths:
    - 'web/**'
    - '.github/workflows/build-frontend.yaml'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Depenedencies
        run: yarn install
        env:
          CI: true
      - name: Code Analysis
        run: make lint_frontend
      - name: Unit Test
        run: make test_frontend
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: ./web
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: golfapipol/poc-kind-action-helm-web
          tag_with_ref: true